### ISSUE TITLE
criar uma pagina para perguntas e respostas

### ISSUE THREAD

**Issue by jeffmaran** [gdgfoz/gdgfoz.github.io#4]
criar pagina para a comunidade fazer perguntas e podermos ir respondendo, pode ser de maneira anonima a pergunta, usar captcha para boots  persistir para podermos criar uma base de conhecimento sobre

**Comment by fernandomantoan** [comment]
Como usaremos o Jekyll, daria pra usar o firebase pra armazenar esses dados

**Comment by jeffmaran** [comment]
eu curti a ideia fernando!
